import AppKit
import AVFoundation
import AVKit
import Observation
import SwiftUI

// MARK: - The recordings on disk

/// The recordings in Movies ▸ CopyWell, for the Recordings section of the main
/// window. The folder is the source of truth: a movie deleted or added in
/// Finder is simply there, or not, the next time it is read.
@MainActor
@Observable
final class RecordingLibrary {
    static let shared = RecordingLibrary()

    struct Recording: Identifiable, Hashable {
        var id: URL { url }
        let url: URL
        let name: String
        let created: Date
        let bytes: Int64
        let duration: TimeInterval
    }

    private(set) var recordings: [Recording] = []
    private(set) var thumbnails: [URL: NSImage] = [:]

    @ObservationIgnored private var loading: Task<Void, Never>?

    private init() {}

    /// Movies ▸ CopyWell. Inside the sandbox the Movies folder is a link out of
    /// the container; it is resolved so the path handed to Finder and to other
    /// apps is the real one.
    static func directory() throws -> URL {
        let movies = FileManager.default.urls(for: .moviesDirectory, in: .userDomainMask)[0]
            .resolvingSymlinksInPath()
            .appendingPathComponent("CopyWell", isDirectory: true)
        try FileManager.default.createDirectory(at: movies, withIntermediateDirectories: true)
        return movies
    }

    static func newRecordingURL() throws -> URL {
        try directory().appendingPathComponent(CaptureNaming.recordingName()).appendingPathExtension("mov")
    }

    func refresh() {
        loading?.cancel()
        loading = Task { await load() }
    }

    private func load() async {
        guard let directory = try? Self.directory(),
              let files = try? FileManager.default.contentsOfDirectory(
                  at: directory,
                  includingPropertiesForKeys: [.creationDateKey, .fileSizeKey],
                  options: [.skipsHiddenFiles]
              ) else {
            recordings = []
            return
        }
        var found: [Recording] = []
        for url in files where ["mov", "mp4", "m4v"].contains(url.pathExtension.lowercased()) {
            let values = try? url.resourceValues(forKeys: [.creationDateKey, .fileSizeKey])
            let duration = (try? await AVURLAsset(url: url).load(.duration).seconds) ?? 0
            found.append(Recording(
                url: url,
                name: url.deletingPathExtension().lastPathComponent,
                created: values?.creationDate ?? .distantPast,
                bytes: Int64(values?.fileSize ?? 0),
                duration: duration.isFinite ? duration : 0
            ))
        }
        guard !Task.isCancelled else { return }
        recordings = found.sorted { $0.created > $1.created }
        thumbnails = thumbnails.filter { key, _ in found.contains { $0.url == key } }

        for recording in recordings where thumbnails[recording.url] == nil {
            if let image = await Self.thumbnail(for: recording.url) {
                thumbnails[recording.url] = image
            }
        }
    }

    /// Dropped after a trim, so the card shows the new first frame.
    func forgetThumbnail(for url: URL) {
        thumbnails[url] = nil
    }

    private static func thumbnail(for url: URL) async -> NSImage? {
        let generator = AVAssetImageGenerator(asset: AVURLAsset(url: url))
        generator.appliesPreferredTrackTransform = true
        generator.maximumSize = CGSize(width: 640, height: 400)
        guard let image = try? await generator.image(at: CMTime(seconds: 0.5, preferredTimescale: 600)).image else {
            return nil
        }
        return NSImage(cgImage: image, size: CGSize(width: image.width, height: image.height))
    }

    // MARK: Actions

    static func copy(_ url: URL) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.writeObjects([url as NSURL])
        PasteboardPrivacy.markAsAutoGenerated(pasteboard)
        CaptureToast.show(L("Recording copied"), symbol: "checkmark.circle.fill")
    }

    static func reveal(_ url: URL) {
        NSWorkspace.shared.activateFileViewerSelecting([url])
    }

    /// To the Trash, not gone: a recording deleted by mistake can be put back.
    func moveToTrash(_ url: URL) {
        NSWorkspace.shared.recycle([url]) { _, _ in
            Task { @MainActor in RecordingLibrary.shared.refresh() }
        }
        recordings.removeAll { $0.url == url }
    }
}

// MARK: - Mixing voice and system sound

/// A recording with both the Mac's sound and a voice has two audio tracks,
/// and most players — browsers, messengers, QuickTime on iPhone — play only
/// the first. They are mixed into one, with the video copied across untouched.
enum RecordingMixdown {
    static func mixAudioIfNeeded(at url: URL) async {
        await Task.detached(priority: .userInitiated) {
            await mix(url)
        }.value
    }

    private static func mix(_ url: URL) async {
        let asset = AVURLAsset(url: url)
        guard let audioTracks = try? await asset.loadTracks(withMediaType: .audio), audioTracks.count > 1,
              let videoTrack = try? await asset.loadTracks(withMediaType: .video).first,
              let formatHint = try? await videoTrack.load(.formatDescriptions).first,
              let reader = try? AVAssetReader(asset: asset) else { return }

        let temporary = url.deletingLastPathComponent()
            .appendingPathComponent(".mix-\(UUID().uuidString).mov")
        guard let writer = try? AVAssetWriter(outputURL: temporary, fileType: .mov) else { return }

        let videoOut = AVAssetReaderTrackOutput(track: videoTrack, outputSettings: nil)
        let audioOut = AVAssetReaderAudioMixOutput(audioTracks: audioTracks, audioSettings: [
            AVFormatIDKey: kAudioFormatLinearPCM,
            AVSampleRateKey: 48_000,
            AVNumberOfChannelsKey: 2,
            AVLinearPCMBitDepthKey: 16,
            AVLinearPCMIsFloatKey: false,
            AVLinearPCMIsBigEndianKey: false,
            AVLinearPCMIsNonInterleaved: false,
        ])
        guard reader.canAdd(videoOut), reader.canAdd(audioOut) else { return }
        reader.add(videoOut)
        reader.add(audioOut)

        let videoIn = AVAssetWriterInput(mediaType: .video, outputSettings: nil, sourceFormatHint: formatHint)
        let audioIn = AVAssetWriterInput(mediaType: .audio, outputSettings: [
            AVFormatIDKey: kAudioFormatMPEG4AAC,
            AVSampleRateKey: 48_000,
            AVNumberOfChannelsKey: 2,
            AVEncoderBitRateKey: 192_000,
        ])
        guard writer.canAdd(videoIn), writer.canAdd(audioIn) else { return }
        writer.add(videoIn)
        writer.add(audioIn)

        guard reader.startReading(), writer.startWriting() else { return }
        writer.startSession(atSourceTime: .zero)

        // Each reader output and writer input is used by exactly one pump.
        nonisolated(unsafe) let pumps: [(AVAssetReaderOutput, AVAssetWriterInput, String)] = [
            (videoOut, videoIn, "video"), (audioOut, audioIn, "audio"),
        ]
        await withTaskGroup(of: Void.self) { group in
            for index in pumps.indices {
                group.addTask {
                    let (output, input, label) = pumps[index]
                    await pump(output, into: input, label: label)
                }
            }
        }

        guard reader.status == .completed else {
            writer.cancelWriting()
            try? FileManager.default.removeItem(at: temporary)
            return
        }
        await writer.finishWriting()
        guard writer.status == .completed else {
            try? FileManager.default.removeItem(at: temporary)
            return
        }
        _ = try? FileManager.default.replaceItemAt(url, withItemAt: temporary)
    }

    private static func pump(_ output: AVAssetReaderOutput, into input: AVAssetWriterInput, label: String) async {
        let queue = DispatchQueue(label: "com.copywell.mix.\(label)")
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            nonisolated(unsafe) let output = output
            nonisolated(unsafe) let input = input
            input.requestMediaDataWhenReady(on: queue) {
                while input.isReadyForMoreMediaData {
                    guard let buffer = output.copyNextSampleBuffer() else {
                        input.markAsFinished()
                        continuation.resume()
                        return
                    }
                    input.append(buffer)
                }
            }
        }
    }
}

// MARK: - The review window

/// Opens when a recording finishes, and from the Recordings section: the
/// movie with a player, trimming, and what can be done with it next.
@MainActor
final class RecordingReview: NSObject, NSWindowDelegate {
    private static var open: [URL: RecordingReview] = [:]

    private let url: URL
    private let window: NSWindow
    private let playerView = AVPlayerView()
    private let player: AVPlayer
    fileprivate let model = ReviewModel()

    static func show(_ url: URL) {
        NSApp.activate(ignoringOtherApps: true)
        if let existing = open[url] {
            existing.window.makeKeyAndOrderFront(nil)
            return
        }
        let review = RecordingReview(url: url)
        open[url] = review
        review.window.center()
        review.window.makeKeyAndOrderFront(nil)
        review.player.play()
    }

    private init(url: URL) {
        self.url = url
        player = AVPlayer(url: url)
        window = NSWindow(
            contentRect: CGRect(x: 0, y: 0, width: 880, height: 580),
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )
        super.init()
        playerView.player = player
        playerView.controlsStyle = .floating
        playerView.showsSharingServiceButton = true
        window.isReleasedWhenClosed = false
        window.title = url.deletingPathExtension().lastPathComponent
        window.minSize = CGSize(width: 520, height: 380)
        window.delegate = self
        window.contentView = NSHostingView(rootView: ReviewView(review: self, playerView: playerView))
    }

    func windowWillClose(_ notification: Notification) {
        player.pause()
        Self.open[url] = nil
    }

    // MARK: Actions

    fileprivate func trim() {
        guard playerView.canBeginTrimming else { return }
        player.pause()
        playerView.beginTrimming { [weak self] result in
            guard result == .okButton else { return }
            MainActor.assumeIsolated { self?.exportTrimmed() }
        }
    }

    private func exportTrimmed() {
        guard let item = player.currentItem else { return }
        let start = item.reversePlaybackEndTime.isValid ? item.reversePlaybackEndTime : .zero
        let end = item.forwardPlaybackEndTime.isValid ? item.forwardPlaybackEndTime : item.duration
        guard end > start else { return }
        let range = CMTimeRange(start: start, end: end)
        let url = self.url
        model.isBusy = true
        Task { @MainActor in
            let trimmed = await Self.export(url, range: range)
            model.isBusy = false
            guard trimmed else {
                let alert = NSAlert()
                alert.messageText = L("The recording could not be trimmed")
                alert.runModal()
                return
            }
            player.replaceCurrentItem(with: AVPlayerItem(url: url))
            RecordingLibrary.shared.forgetThumbnail(for: url)
            RecordingLibrary.shared.refresh()
            CaptureToast.show(L("Recording trimmed"), symbol: "scissors")
        }
    }

    /// Replaces the file with the chosen part of it. Re-encoded rather than
    /// copied, so the cut lands on the frame chosen and not on the keyframe
    /// before it.
    static func export(_ url: URL, range: CMTimeRange) async -> Bool {
        let temporary = url.deletingLastPathComponent().appendingPathComponent(".trim-\(UUID().uuidString).mov")
        let asset = AVURLAsset(url: url)
        for preset in [AVAssetExportPresetHighestQuality, AVAssetExportPresetHEVCHighestQuality, AVAssetExportPresetPassthrough] {
            guard let session = AVAssetExportSession(asset: asset, presetName: preset) else { continue }
            session.outputURL = temporary
            session.outputFileType = .mov
            session.timeRange = range
            nonisolated(unsafe) let exporting = session
            await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
                exporting.exportAsynchronously { continuation.resume() }
            }
            if session.status == .completed {
                return (try? FileManager.default.replaceItemAt(url, withItemAt: temporary)) != nil
            }
            try? FileManager.default.removeItem(at: temporary)
        }
        return false
    }

    fileprivate func copy() { RecordingLibrary.copy(url) }

    fileprivate func reveal() { RecordingLibrary.reveal(url) }

    fileprivate func moveToTrash() {
        player.pause()
        RecordingLibrary.shared.moveToTrash(url)
        window.close()
        CaptureToast.show(L("Moved to the Trash"), symbol: "trash")
    }
}

@MainActor
@Observable
fileprivate final class ReviewModel {
    var isBusy = false
}

private struct PlayerHost: NSViewRepresentable {
    let playerView: AVPlayerView
    func makeNSView(context: Context) -> AVPlayerView { playerView }
    func updateNSView(_ nsView: AVPlayerView, context: Context) {}
}

private struct ReviewView: View {
    let review: RecordingReview
    let playerView: AVPlayerView

    var body: some View {
        VStack(spacing: 0) {
            PlayerHost(playerView: playerView)
                .background(Color.black)
            Divider()
            HStack(spacing: 10) {
                Button { review.trim() } label: {
                    Label(L("Trim…"), systemImage: "scissors")
                }
                Button { review.copy() } label: {
                    Label(L("Copy"), systemImage: "doc.on.doc")
                }
                Button { review.reveal() } label: {
                    Label(L("Show in Finder"), systemImage: "folder")
                }
                Spacer()
                if review.model.isBusy {
                    ProgressView().controlSize(.small)
                }
                Button(role: .destructive) { review.moveToTrash() } label: {
                    Label(L("Move to Trash"), systemImage: "trash")
                }
            }
            .disabled(review.model.isBusy)
            .padding(12)
        }
        .frame(minWidth: 520, minHeight: 380)
    }
}
